Dockerfile

FROM openjdk:22-jdk-buster

WORKDIR /applications

RUN apt-get update && apt-get install -y wget

RUN wget -O applications.jar https://github.com/dhanyesh/dockerdemo/raw/main/HelloWorld-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java", "-jar", "applications.jar"]
